version: '3.9'

services:
  testdb:
    image: postgres:15-alpine
    environment:
      POSTGRES_PASSWORD: rc
      POSTGRES_USER: rc
      POSTGRES_DB: rc
    ports:
      - "5432:5432"
    volumes:
      - test_db_data:/var/lib/postgresql/data

volumes:
  test_db_data: