name: CI Tests

on: [push]

jobs:
  test:
    runs-on: ubuntu-latest

    steps:
      - name: Checkout
        uses: actions/checkout@v3

      - name: Prepare java
        uses: actions/setup-java@v3
        with:
          distribution: 'zulu'
          java-version: '17'

      - name: Setup Clojure
        uses: DeLaGuardo/setup-clojure@10.3
        with:
          tools-deps: '1.11.1.1273'

      - name: Launch docker-compose
        run: docker-compose up -d

      - name: Run test suite
        run: clojure -M:test